config/routes.rb
Rails.application.routes.draw do
  # root "articles#index"
  root "books#searchBooks"
  
  resources :books
  resources :bookshelves
  devise_for :users



  get "/searchbyauthor" => "books#searchByAuthor"
  get "/searchbooks" => "books#searchBooks"
  get "/searchbookresults" => "books#searchBookResults"
  get "/:username" => "users#show", as: :user

  
end

app/views/shared/_breadcrumbs.html.erb
<% if @breadcrumbs.present? %>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <% @breadcrumbs.each do |breadcrumb| %>
        <% if breadcrumb == @breadcrumbs.last %>
          <li class="breadcrumb-item active" aria-current="page">
            <%= breadcrumb.fetch(:content) %>
          </li>
        <% else %>
          <li class="breadcrumb-item">
            <%= link_to breadcrumb.fetch(:content), breadcrumb[:href] %>
          </li>
        <% end %>
      <% end %>
    </ol>
  </nav>
<% end %>

app/views/shared/_cdn_assets.html.erb
<!-- app/views/shared/_cdn_assets.html.erb -->

<!-- Connect Bootstrap CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css">

<!-- Connect Bootstrap JavaScript and its dependencies -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>

<!-- Connect Font Awesome -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/js/all.min.js"></script>

app/views/shared/_flash.html.erb
<div class="alert alert-<%= css_class %> alert-dismissible fade show" role="alert">
  <%= message %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Shelvz</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav me-auto">
      <% if current_user%>
          <li class="nav-item">
            <%= link_to user_path(current_user.username), class: "nav-link" do %>
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M9 3v15h3V3H9m3 2l4 13l3-1l-4-13l-3 1M5 5v13h3V5H5M3 19v2h18v-2H3Z"/></svg>
              Bookshelves
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to searchbooks_path, class: "nav-link"  do %><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M5 11a6 6 0 1 1 12 0a6 6 0 0 1-12 0zm6-8a8 8 0 1 0 4.906 14.32l3.387 3.387a1 1 0 0 0 1.414-1.414l-3.387-3.387A8 8 0 0 0 11 3zm0 12a4 4 0 1 0 0-8a4 4 0 0 0 0 8z" clip-rule="evenodd"/></svg>Search<%end%>
          </li>
        <% end %>
      </ul>
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Edit #{current_user.username}", edit_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>

        <% end %>
      </ul>
    </div>
  </div>
</nav>